# ~/.bashrc: executed by bash(1) for non-login shells.

# User Specific aliases
alias ll="ls -l"
alias la="ls -A"
alias lla="ls -la"

# use vim as standard editor
export EDITOR=/usr/bin/vim

# enable coloring
export CLICOLOR=1
export LSCOLORS=gxfxbEaEBxxEhEhBaDaCaD
